# Generated by Django 4.2.5 on 2023-10-03 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.BooleanField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pyme', models.ForeignKey(db_column='pyme', on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('porcentaje', models.FloatField()),
                ('pyme', models.ForeignKey(db_column='pyme', on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.pyme')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Pyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyme', models.ForeignKey(db_column='pyme', on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencia', to='rest_api.pyme')),
                ('rut_cliente', models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.cliente')),
            ],
        ),
    ]
